# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 06:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('braintree_id', models.CharField(max_length=50, unique=True)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fax', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=14)),
                ('updated_at', models.DateTimeField(null=True)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('entity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('braintree_id', models.CharField(max_length=50, unique=True)),
                ('additional_processor_response', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('amount_refunded', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('avs_error_response_code', models.CharField(blank=True, max_length=50)),
                ('avs_postal_code_response_code', models.CharField(blank=True, choices=[(b'M', b'Matches'), (b'N', b'Does not Match'), (b'U', b'Not Verified'), (b'I', b'Not Provided'), (b'A', b'Not Applicable')], max_length=1)),
                ('avs_street_address_response_code', models.CharField(blank=True, choices=[(b'M', b'Matches'), (b'N', b'Does not Match'), (b'U', b'Not Verified'), (b'I', b'Not Provided'), (b'A', b'Not Applicable')], max_length=1)),
                ('channel', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('currency_iso_code', models.CharField(blank=True, max_length=3)),
                ('cvv_response_code', models.CharField(blank=True, choices=[(b'M', b'Matches'), (b'N', b'Does not Match'), (b'U', b'Not Verified'), (b'I', b'Not Provided'), (b'A', b'Not Applicable')], max_length=1)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('funds_held', models.CharField(blank=True, max_length=200)),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('settlement_currency_exchange_rate', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('settlement_currency_iso_code', models.CharField(blank=True, max_length=3)),
                ('disbursement_success', models.NullBooleanField()),
                ('escrow_status', models.CharField(blank=True, choices=[(b'hold_pending', b'hold_pending'), (b'held', b'held'), (b'release_pending', b'release_pending'), (b'released', b'released'), (b'refunded', b'refunded')], max_length=40)),
                ('gateway_rejection_reason', models.CharField(blank=True, choices=[(b'avs', b'avs'), (b'avs_and_cvv', b'avs_and_cvv'), (b'cvv', b'cvv'), (b'duplicate', b'duplicate'), (b'fraud', b'fraud'), (b'three_d_secure', b'three_d_secure'), (b'application_incomplete', b'application_incomplete')], max_length=60)),
                ('merchant_account_id', models.CharField(blank=True, max_length=50)),
                ('order_id', models.CharField(blank=True, max_length=200)),
                ('payment_instrument_type', models.CharField(blank=True, max_length=100)),
                ('authorization_id', models.CharField(blank=True, max_length=200)),
                ('capture_id', models.CharField(blank=True, max_length=200)),
                ('payer_email', models.CharField(blank=True, max_length=200)),
                ('payer_first_name', models.CharField(blank=True, max_length=200)),
                ('payer_id', models.CharField(blank=True, max_length=200)),
                ('payer_last_name', models.CharField(blank=True, max_length=200)),
                ('payment_id', models.CharField(blank=True, max_length=200)),
                ('refund_id', models.CharField(blank=True, max_length=200)),
                ('seller_protection_status', models.CharField(blank=True, max_length=200)),
                ('tax_id_type', models.CharField(blank=True, max_length=200)),
                ('transaction_fee_amount', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('transaction_fee_currency_iso_code', models.CharField(blank=True, max_length=200)),
                ('plan_id', models.CharField(blank=True, max_length=255)),
                ('processor_authorization_code', models.CharField(blank=True, max_length=100)),
                ('processor_response_code', models.CharField(blank=True, max_length=40)),
                ('processor_response_text', models.CharField(blank=True, max_length=255)),
                ('processor_settlement_response_code', models.CharField(blank=True, max_length=40)),
                ('processor_settlement_response_text', models.CharField(blank=True, max_length=255)),
                ('purchase_order_number', models.CharField(blank=True, max_length=54)),
                ('recurring', models.NullBooleanField()),
                ('refund_ids', models.TextField(blank=True)),
                ('refunded_transaction_id', models.CharField(blank=True, max_length=40)),
                ('decision', models.CharField(blank=True, max_length=40)),
                ('risk_data_id', models.CharField(blank=True, max_length=200)),
                ('service_fee_amount', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('settlement_batch_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, choices=[(b'authorization_expired', b'authorization_expired'), (b'authorized', b'authorized'), (b'authorizing', b'authorizing'), (b'failed', b'failed'), (b'gateway_rejected', b'gateway_rejected'), (b'processor_declined', b'processor_declined'), (b'settled', b'settled'), (b'settlement_confirmed', b'settlement_confirmed'), (b'settlement_declined', b'settlement_declined'), (b'settlement_failed', b'settlement_failed'), (b'settlement_pending', b'settlement_pending'), (b'settling', b'settling'), (b'submitted_for_settlement', b'submitted_for_settlement'), (b'voided', b'voided'), (b'unrecognized', b'unrecognized')], max_length=100)),
                ('status_history', models.CharField(blank=True, max_length=255)),
                ('billing_period_end_date', models.DateTimeField(null=True)),
                ('billing_period_start_date', models.DateTimeField(null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=200)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('tax_exempt', models.NullBooleanField()),
                ('enrolled', models.CharField(blank=True, choices=[(b'Y', b'Yes'), (b'N', b'No'), (b'U', b'Unavailable'), (b'B', b'Bypass'), (b'E', b'RequestFailure')], max_length=1)),
                ('liability_shift_possible', models.NullBooleanField()),
                ('liability_shifted', models.NullBooleanField()),
                ('three_d_secure_status', models.CharField(blank=True, max_length=200)),
                ('transaction_type', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(null=True)),
                ('voice_referral_number', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=80)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='djbraintree.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
